### ISSUE TITLE
[Not issue]Can you tell me how to build it to rpm?

### ISSUE THREAD

**Issue by 0312birdzhang** [CODeRUS/jolla-settings-powersave#1]
Thank you very much :smile:

**Comment by CODeRUS** [comment]
Open project in sailfish sdk and press button build

**Comment by 0312birdzhang** [comment]
:joy: I know how to use Sailfish SDK,but your project it not used .pro file.
So,do you mean what i want to say?

**Comment by CODeRUS** [comment]
ah, my project  :joy:
you need to login to mersdk and compile with mb/mb2 command

**Comment by 0312birdzhang** [comment]
mb/mb2 command? :dizzy_face:

**Comment by CODeRUS** [comment]
https://wiki.merproject.org/wiki/Sailfish_SDK_Hacks

**Comment by 0312birdzhang** [comment]
Thank you very much :kissing_heart:
