### ISSUE TITLE
Добавить описание режима powersave

### ISSUE THREAD

**Issue by petRUShka** [CODeRUS/jolla-settings-powersave#2]
Сейчас непонятно, в чём конкретно заключается "powersave". Неясно, за счёт чего именно будет осуществляться экономия. 

Большая просьба пояснить это где-нибудь в Readme или в about

**Comment by CODeRUS** [comment]
powersave как powersave. а как он работает - хер его знает.

**Comment by petRUShka** [comment]
А никакой документации Jolla на эту тему нет? А как по ощущениям, действительно экономит?

**Comment by CODeRUS** [comment]
Try http://together.jolla.com
